/*
 * Marketo Rest API
 *
 * Marketo Rest API
 *
 * API version: 1.0
 * Contact: developerfeedback@marketo.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ActivityType struct {

	ApiName string `json:"apiName,omitempty"`

	// List of secondary attributes of the type
	Attributes []ActivityTypeAttribute `json:"attributes"`

	// Description of the activity type
	Description string `json:"description,omitempty"`

	// Id of the activity type
	Id int32 `json:"id"`

	// Name of the activity type
	Name string `json:"name"`

	// Primary attribute of the type
	PrimaryAttribute *ActivityTypeAttribute `json:"primaryAttribute"`
}
