/*
 * Marketo Rest API
 *
 * Marketo Rest API
 *
 * API version: 1.0
 * Contact: developerfeedback@marketo.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ActivityTypeAttribute struct {

	ApiName string `json:"apiName,omitempty"`

	// Datatype of the Attribute
	DataType string `json:"dataType"`

	// Name of the attribute
	Name string `json:"name"`
}
