/*
 * Marketo Rest API
 *
 * Marketo Rest API
 *
 * API version: 1.0
 * Contact: developerfeedback@marketo.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ChangeLeadProgramStatusRequest struct {

	// List of leads for input
	Input []LeadLookupInputData `json:"input"`

	// Program status of the record.  Permissible values can be retrieve from the Get Channel by Name API for the designated program's channel
	Status string `json:"status"`
}
