/*
 * Marketo Rest API
 *
 * Marketo Rest API
 *
 * API version: 1.0
 * Contact: developerfeedback@marketo.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ChangeLeadProgramStatusOutputData struct {

	// Unique integer id of a lead record
	Id int64 `json:"id"`

	// List of reasons why an operation did not succeed.  Reasons are only present in API responses and should not be submitted
	Reasons []Reason `json:"reasons,omitempty"`

	// Program status of the record.  Permissible values can be retrieve from the Get Channel by Name API for the designated program's channel
	Status string `json:"status"`
}
