/*
 * Marketo Rest API
 *
 * Marketo Rest API
 *
 * API version: 1.0
 * Contact: developerfeedback@marketo.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Company record.  May include any additional fields listed in the corresponding describe method
type Company struct {

	// Unique integer id of the company record
	Id int64 `json:"id"`

	Reasons []Reason `json:"reasons,omitempty"`

	// Integer indicating the sequence of the record in response.  This value is correlated to the order of the records included in the request input.  Seq should only be part of responses and should not be submitted.
	Seq int32 `json:"seq"`

	// Status of the operation performed on the record
	Status string `json:"status,omitempty"`
}
