/*
 * Marketo Rest API
 *
 * Marketo Rest API
 *
 * API version: 1.0
 * Contact: developerfeedback@marketo.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type CustomActivityTypeRequest struct {

	ApiName string `json:"apiName"`

	Description string `json:"description,omitempty"`

	// Human-readable name of the associated filter
	FilterName string `json:"filterName"`

	// Human-readable display name of the activity type
	Name string `json:"name"`

	// Primary attribute of the activity type
	PrimaryAttribute *CustomActivityTypeAttribute `json:"primaryAttribute"`

	// Human-readable name of the associated trigger
	TriggerName string `json:"triggerName"`
}
