/*
 * Marketo Rest API
 *
 * Marketo Rest API
 *
 * API version: 1.0
 * Contact: developerfeedback@marketo.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type CustomObject struct {

	// Unique GUID of the custom object records
	MarketoGUID string `json:"marketoGUID"`

	Reasons []Reason `json:"reasons,omitempty"`

	// Integer indicating the sequence of the record in response.  This value is correlated to the order of the records included in the request input.  Seq should only be part of responses and should not be submitted.
	Seq int32 `json:"seq"`
}
