/*
 * Marketo Rest API
 *
 * Marketo Rest API
 *
 * API version: 1.0
 * Contact: developerfeedback@marketo.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type CustomActivityTypeAttributeRequest struct {

	// List of attributes to add to the activity type
	Attributes []CustomActivityTypeAttribute `json:"attributes,omitempty"`
}
