/*
 * Marketo Rest API
 *
 * Marketo Rest API
 *
 * API version: 1.0
 * Contact: developerfeedback@marketo.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type CustomActivityType struct {

	// API Name of the type.  The API name must be unique and alphanumeric, containing at least one letter.  It is highly recommended to prepend a unique namespace of up to sixteen characters to the API name.  Required on creation
	ApiName string `json:"apiName,omitempty"`

	// List of attributes for the activity type.  May only be added or update through Create or Update Custom Activity Type Attributes
	Attributes []CustomActivityTypeAttribute `json:"attributes,omitempty"`

	// Datetime when the activity type was created
	CreatedAt string `json:"createdAt,omitempty"`

	// Description of the activity type
	Description string `json:"description,omitempty"`

	// Human-readable name for the associated filter of the activity type.  Required on creation
	FilterName string `json:"filterName,omitempty"`

	Id int32 `json:"id,omitempty"`

	// Human-readable display name of the type.  Required on creation
	Name string `json:"name,omitempty"`

	// Primary Attribute of the activity type.  Required on creation
	PrimaryAttribute *CustomActivityTypeAttribute `json:"primaryAttribute,omitempty"`

	// State of the activity type
	Status string `json:"status,omitempty"`

	// Human-readable name for the associated trigger of the activity type.  Required on creation
	TriggerName string `json:"triggerName,omitempty"`

	// Datetime when the activity type was most recently updated
	UpdatedAt string `json:"updatedAt,omitempty"`
}
