/*
 * Marketo Rest API
 *
 * Marketo Rest API
 *
 * API version: 1.0
 * Contact: developerfeedback@marketo.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type DateRange struct {

	// End of date range filter (ISO 8601-format)
	EndAt string `json:"endAt,omitempty"`

	// Start of date range filter (ISO-8601 format)
	StartAt string `json:"startAt,omitempty"`
}
