/*
 * Marketo Rest API
 *
 * Marketo Rest API
 *
 * API version: 1.0
 * Contact: developerfeedback@marketo.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type DeleteCompanyRequest struct {

	// Field to delete company records by.  Key may be \"dedupeFields\" or \"idField\"
	DeleteBy string `json:"deleteBy,omitempty"`

	// List of company records. Companies in the list should only contain a member matching the dedupeBy value
	Input []Company `json:"input,omitempty"`
}
