/*
 * Marketo Rest API
 *
 * Marketo Rest API
 *
 * API version: 1.0
 * Contact: developerfeedback@marketo.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type DeleteCustomObjectRequest struct {

	// Field to delete records by.  Permissible values are idField or dedupeFields as indicated by the result of the corresponding describe record
	DeleteBy string `json:"deleteBy,omitempty"`

	// List of input records
	Input []CustomObject `json:"input"`
}
