/*
 * Marketo Rest API
 *
 * Marketo Rest API
 *
 * API version: 1.0
 * Contact: developerfeedback@marketo.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ExportActivityRequest struct {

	// File header field names override (corresponds with REST API name)
	ColumnHeaderNames *ColumnHeaderNames `json:"columnHeaderNames,omitempty"`

	// Comma-separated list of fields to include in the file
	Fields []string `json:"fields"`

	// Record selection criteria. \"createAt\" is required, \"activityTypeIds\" is optional
	Filter *ExportActivityFilter `json:"filter"`

	// File format to create(\"CSV\", \"TSV\", \"SSV\").  Default is \"CSV\"
	Format string `json:"format,omitempty"`
}
