/*
 * Marketo Rest API
 *
 * Marketo Rest API
 *
 * API version: 1.0
 * Contact: developerfeedback@marketo.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ExportActivityFilter struct {

	// List of activity type ids to filter on
	ActivityTypeIds []int32 `json:"activityTypeIds,omitempty"`

	// Date range to filter new activities on
	CreatedAt *DateRange `json:"createdAt"`
}
