/*
 * Marketo Rest API
 *
 * Marketo Rest API
 *
 * API version: 1.0
 * Contact: developerfeedback@marketo.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

// Response containing export job status information
type ExportResponse struct {

	// Date when the export request was created
	CreatedAt time.Time `json:"createdAt,omitempty"`

	// Error message in case of \"Failed\" status
	ErrorMsg string `json:"errorMsg,omitempty"`

	// Unique id of the export job
	ExportId string `json:"exportId"`

	// Size of file in bytes. This will have a value only when status is \"Completed\", otherwise null
	FileSize int64 `json:"fileSize,omitempty"`

	// Finish time of export job. This will have value only when status is \"Completed\" or \"Failed\", otherwise null
	FinishedAt time.Time `json:"finishedAt,omitempty"`

	// Format of file as given in the request (\"CSV\", \"TSV\", \"SSV\")
	Format string `json:"format,omitempty"`

	// Number of records in the export file.  This will have value only when status is \"Completed\", otherwise null
	NumberOfRecords int64 `json:"numberOfRecords,omitempty"`

	// Queue time of export job. This will have value when \"Queued\" status is reached, before that null
	QueuedAt time.Time `json:"queuedAt,omitempty"`

	// Start time of export job. This will have value when \"Processing\" status is reached, before that null
	StartedAt time.Time `json:"startedAt,omitempty"`

	// Status of the export job (\"Created\",\"Queued\",\"Processing\",\"Canceled\",\"Completed\",\"Failed\")
	Status string `json:"status"`
}
