/*
 * Marketo Rest API
 *
 * Marketo Rest API
 *
 * API version: 1.0
 * Contact: developerfeedback@marketo.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Lead record containing only lead id
type InputLead struct {

	// Unique integer id of a lead record
	Id int64 `json:"id"`
}
