/*
 * Marketo Rest API
 *
 * Marketo Rest API
 *
 * API version: 1.0
 * Contact: developerfeedback@marketo.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type InputStreamRangeContent struct {

	ContentType string `json:"contentType,omitempty"`

	FileRange *FileRange `json:"fileRange,omitempty"`

	InputStream *InputStream `json:"inputStream,omitempty"`

	Length int64 `json:"length,omitempty"`
}
