/*
 * Marketo Rest API
 *
 * Marketo Rest API
 *
 * API version: 1.0
 * Contact: developerfeedback@marketo.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Lead record.  Always contains id, but may have any number of other fields, depending on the fields available in the target instance.
type Lead struct {

	// Unique integer id of a lead record
	Id int32 `json:"id"`

	// Membership data for the parent program.  Only returned via Get Leads By Program Id
	Membership *ProgramMembership `json:"membership,omitempty"`

	// Reason object describing why an operation did not succeed for a record
	Reason *Reason `json:"reason,omitempty"`

	// Status of the operation performed on the record
	Status string `json:"status,omitempty"`
}
