/*
 * Marketo Rest API
 *
 * Marketo Rest API
 *
 * API version: 1.0
 * Contact: developerfeedback@marketo.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type LeadAttribute struct {

	// Datatype of the field
	DataType string `json:"dataType"`

	// UI display-name of the field
	DisplayName string `json:"displayName"`

	// Unique integer id of the field
	Id int32 `json:"id"`

	// Max length of the field.  Only applicable to text, string, and text area.
	Length int32 `json:"length,omitempty"`

	// Description of REST API usage attributes
	Rest *LeadMapAttribute `json:"rest,omitempty"`

	// Description of SOAP API usage attributes
	Soap *LeadMapAttribute `json:"soap,omitempty"`
}
