/*
 * Marketo Rest API
 *
 * Marketo Rest API
 *
 * API version: 1.0
 * Contact: developerfeedback@marketo.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Activity record containing information on a data value change
type LeadChangeField struct {

	// Unique integer id of the change record
	Id int32 `json:"id"`

	// Name of the field which was changed
	Name string `json:"name"`

	// New value after the change
	NewValue string `json:"newValue"`

	// Old value before the change
	OldValue string `json:"oldValue,omitempty"`
}
