/*
 * Marketo Rest API
 *
 * Marketo Rest API
 *
 * API version: 1.0
 * Contact: developerfeedback@marketo.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type LeadMapAttribute struct {

	// Name of the attribute
	Name string `json:"name"`

	// Whether the attribute is read only
	ReadOnly bool `json:"readOnly,omitempty"`
}
