/*
 * Marketo Rest API
 *
 * Marketo Rest API
 *
 * API version: 1.0
 * Contact: developerfeedback@marketo.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ListOperationOutputData struct {

	// Unique integer id of a lead record
	Id int64 `json:"id"`

	// List of reasons why an operation did not succeed.  Reasons are only present in API responses and should not be submitted
	Reasons []Reason `json:"reasons,omitempty"`

	// Status of the operation performed on the record
	Status string `json:"status,omitempty"`
}
