/*
 * Marketo Rest API
 *
 * Marketo Rest API
 *
 * API version: 1.0
 * Contact: developerfeedback@marketo.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type LookupCustomObjectRequest struct {

	// Maximum number of records to return in the response.  Max and default is 300
	BatchSize int32 `json:"batchSize,omitempty"`

	// Comma-separated list of fields to include in the response
	Fields []string `json:"fields,omitempty"`

	// Field to search on
	FilterType string `json:"filterType,omitempty"`

	// Input list of records.  When using a single key, the list is a comma-separated list of values.  When using a compound key, the request must be sent as a JSON object, and each record must include each of the fields in the compound key.  Compound keys are determined by the contents of \"dedupeFields\" in the describe result for the object
	Input []CustomObject `json:"input,omitempty"`

	// Paging token returned from a previous response
	NextPageToken string `json:"nextPageToken,omitempty"`
}
