/*
 * Marketo Rest API
 *
 * Marketo Rest API
 *
 * API version: 1.0
 * Contact: developerfeedback@marketo.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ModelError struct {

	// Integer error code of the error
	Code int32 `json:"code"`

	// Message describing the cause of the Error
	Message string `json:"message"`
}
