/*
 * Marketo Rest API
 *
 * Marketo Rest API
 *
 * API version: 1.0
 * Contact: developerfeedback@marketo.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type NamedAccountList struct {

	// Datetime when the named account list was created
	CreatedAt string `json:"createdAt,omitempty"`

	// Unique GUID of the custom object records
	MarketoGUID string `json:"marketoGUID"`

	// Name of named account list
	Name string `json:"name,omitempty"`

	Reasons []Reason `json:"reasons,omitempty"`

	// Integer indicating the sequence of the record in response.  This value is correlated to the order of the records included in the request input.  Seq should only be part of responses and should not be submitted.
	Seq int32 `json:"seq"`

	Status string `json:"status,omitempty"`

	// Type of named account list (\"default\" if created by user or API, \"external\" if managed by CRM-View)
	Type_ string `json:"type,omitempty"`

	// Whether the list is updateable (true if created by user or API, false if managed by CRM-View)
	Updateable bool `json:"updateable,omitempty"`

	// Datetime when the named account list was most recently updated
	UpdatedAt string `json:"updatedAt,omitempty"`
}
