/*
 * Marketo Rest API
 *
 * Marketo Rest API
 *
 * API version: 1.0
 * Contact: developerfeedback@marketo.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ObjectRelation struct {

	// Name of the object relationship field
	Field string `json:"field,omitempty"`

	// Object to which the field is linked
	RelatedTo *RelatedObject `json:"relatedTo,omitempty"`

	// Type of the relationship field
	Type_ string `json:"type,omitempty"`
}
