/*
 * Marketo Rest API
 *
 * Marketo Rest API
 *
 * API version: 1.0
 * Contact: developerfeedback@marketo.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

type ObjectMetaData struct {

	// Datetime when the object type was created
	CreatedAt time.Time `json:"createdAt,omitempty"`

	// List of dedupe fields.  Arrays with multiple members are compound keys
	DedupeFields []string `json:"dedupeFields,omitempty"`

	// Description of the object type
	Description string `json:"description,omitempty"`

	// UI display-name of the object type
	DisplayName string `json:"displayName,omitempty"`

	// List of fields available on the object type
	Fields []ObjectField `json:"fields,omitempty"`

	// Primary id key of the object type
	IdField string `json:"idField,omitempty"`

	// Name of the object type
	Name string `json:"name,omitempty"`

	// List of relationships which the object has
	Relationships []ObjectRelation `json:"relationships,omitempty"`

	// List of fields valid for use as a filter type in a query
	SearchableFields [][]string `json:"searchableFields,omitempty"`

	// Datetime when the object type was most recently updated
	UpdatedAt time.Time `json:"updatedAt,omitempty"`
}
