/*
 * Marketo Rest API
 *
 * Marketo Rest API
 *
 * API version: 1.0
 * Contact: developerfeedback@marketo.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ProgramMembership struct {

	// Whether the lead was acquired by the parent program
	AcquiredBy bool `json:"acquiredBy,omitempty"`

	// Whether the lead is currently exhausted in the stream, if applicable
	IsExhausted bool `json:"isExhausted,omitempty"`

	// Date the lead first became a member of the program
	MembershipDate string `json:"membershipDate"`

	// Cadence of the parent stream if applicable
	NurtureCadence string `json:"nurtureCadence,omitempty"`

	// Program status of the lead in the parent program
	ProgressionStatus string `json:"progressionStatus"`

	// Whether the lead is in a success-status in the parent program
	ReachedSuccess bool `json:"reachedSuccess,omitempty"`

	// Stream that the lead is a member of, if the parent program is an engagement program
	Stream string `json:"stream,omitempty"`
}
