/*
 * Marketo Rest API
 *
 * Marketo Rest API
 *
 * API version: 1.0
 * Contact: developerfeedback@marketo.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Reason struct {

	// Integer code of the reason
	Code string `json:"code"`

	// Message describing the reason for the status of the operation
	Message string `json:"message"`
}
