/*
 * Marketo Rest API
 *
 * Marketo Rest API
 *
 * API version: 1.0
 * Contact: developerfeedback@marketo.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type RelatedObject struct {

	// Foreign field to which the parent is linked
	Field string `json:"field,omitempty"`

	// Name of the link object type
	Name string `json:"name,omitempty"`
}
