/*
 * Marketo Rest API
 *
 * Marketo Rest API
 *
 * API version: 1.0
 * Contact: developerfeedback@marketo.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type SalesPerson struct {

	// Unique integer id of the salesperson record
	Id int64 `json:"id,omitempty"`

	// List of reasons why an operation did not succeed.  Reasons are only present in API responses and should not be submitted
	Reasons []Reason `json:"reasons,omitempty"`

	// Integer indicating the sequence of the record in response.  This value is correlated to the order of the records included in the request input.  Seq should only be part of responses and should not be submitted.
	Seq int32 `json:"seq,omitempty"`

	// Status of the operation performed on the record
	Status string `json:"status,omitempty"`
}
