/*
 * Marketo Rest API
 *
 * Marketo Rest API
 *
 * API version: 1.0
 * Contact: developerfeedback@marketo.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

type ScheduleCampaignData struct {

	// Name of the resulting program.  When set, this attribute will cause the campaign, parent program, and all of its assets, to be created with the resulting new name.  The parent program will be cloned and the newly created campaign will be scheduled.  The resulting program is created underneath the parent.  Programs with snippets, push notifications, in-app messages, static lists, reports, and social assets may not be cloned in this way
	CloneToProgramName string `json:"cloneToProgramName,omitempty"`

	// Datetime to run the campaign at.  If unset, the campaign will be run five minutes after the call is made
	RunAt time.Time `json:"runAt,omitempty"`

	// List of my tokens to replace during the run of the target campaign.  The tokens must be available in a parent program or folder to be replaced during the run
	Tokens []Token `json:"tokens,omitempty"`
}
