/*
 * Marketo Rest API
 *
 * Marketo Rest API
 *
 * API version: 1.0
 * Contact: developerfeedback@marketo.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Record describe how to schedule the campaign
type ScheduleCampaignRequest struct {

	Input *ScheduleCampaignData `json:"input,omitempty"`
}
