/*
 * Marketo Rest API
 *
 * Marketo Rest API
 *
 * API version: 1.0
 * Contact: developerfeedback@marketo.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type SyncCompanyRequest struct {

	// Type of sync operation to perform
	Action string `json:"action,omitempty"`

	// Field to deduplicate on.  If the value in the field for a given record is not unique, an error will be returned for the individual record.
	DedupeBy string `json:"dedupeBy,omitempty"`

	// List of input records
	Input []Company `json:"input,omitempty"`
}
