/*
 * Marketo Rest API
 *
 * Marketo Rest API
 *
 * API version: 1.0
 * Contact: developerfeedback@marketo.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type TriggerCampaignRequest struct {

	// Object describing trigger configuration for the campaign
	Input *TriggerCampaignData `json:"input"`
}
