/*
 * Marketo Rest API
 *
 * Marketo Rest API
 *
 * API version: 1.0
 * Contact: developerfeedback@marketo.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type UserCount struct {

	// Number of calls made in the time period
	Count int32 `json:"count"`

	// Id of the user
	UserId string `json:"userId"`
}
