/*
 * Marketo Rest API
 *
 * Marketo Rest API
 *
 * API version: 1.0
 * Contact: developerfeedback@marketo.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Warning struct {

	// Integer code of the warning
	Code int32 `json:"code"`

	// Message describing the warning
	Message string `json:"message"`
}
